[profile.default]
solc = "0.8.23"
src = "src"
out = "out"
auto_detect_remappings = false
libs = ["lib"]
# remappings = [
#   '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
#   '@solmate/=lib/solmate/src/'
# ]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
